version: '3'
services:
    frontend:
        build: images/apache
        image: onyx/ddd-analyzer
        volumes:
            - ..:/var/www/app
            - ../system/bash-history/.frontend:/root/.bash_history
        ports:
            - "${WEB_PORT}:80"
            - "${WEB_SSL_PORT}:443"
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
